h10-core/main/default/objects/Callout_Log__c/Callout_Log__c.object-meta.xml
<CustomObject>
    <description>Stores the callout logs</description>
    <label>Callout Log</label>
    <nameField>
        <displayFormat>CLOG-{000000}</displayFormat>
        <label>Callout Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Callout Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

h10-core/main/default/objects/Callout_Log__c/fields/Callout_Time__c.field-meta.xml
<CustomField>
    <fullName>Callout_Time__c</fullName>
    <description>Stores the time spent in the callout</description>
    <label>Callout Time</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

h10-core/main/default/objects/Callout_Log__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <description>Stores the request endpoint</description>
    <label>Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

h10-core/main/default/objects/Callout_Log__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <description>Stores the HTTP Method used in the callout</description>
    <label>Method</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

h10-core/main/default/objects/Callout_Log__c/fields/Related_To__c.field-meta.xml
<CustomField>
    <fullName>Related_To__c</fullName>
    <description>Related to object Id</description>
    <label>Related To</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

h10-core/main/default/objects/Callout_Log__c/fields/Request_Body__c.field-meta.xml
<CustomField>
    <fullName>Request_Body__c</fullName>
    <description>Stores the request body</description>
    <label>Request Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

h10-core/main/default/objects/Callout_Log__c/fields/Response_Body__c.field-meta.xml
<CustomField>
    <fullName>Response_Body__c</fullName>
    <description>Stores the response body</description>
    <label>Response Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

h10-core/main/default/objects/Callout_Log__c/fields/Response_Status_Code__c.field-meta.xml
<CustomField>
    <fullName>Response_Status_Code__c</fullName>
    <description>Stores the HTTP status code</description>
    <label>Response Status Code</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

h10-core/main/default/classes/Callout.cls
public without sharing class Callout {

    private Callout(){}

    private static Callout instance;

    public static Callout getInstance(){
        if (instance == null) { instance = new Callout(); }
        return instance;
    }

    public HttpResponse send(HttpRequest request, Id relatedTo) {

        try {
            Http http = new Http();

            Long requestStart = System.Now().getTime();
            HttpResponse response = http.send(request);
            Long requestEnd = System.Now().getTime();

            insert new Callout_Log__c(
                          Related_To__c = relatedTo,
                            Endpoint__c = request.getEndpoint(),
                              Method__c = request.getMethod(),
                        Request_Body__c = request.getBody()?.left(131072),
                       Response_Body__c = response.getBody()?.left(131072),
                Response_Status_Code__c = response.getStatusCode(), 
                        Callout_Time__c = (requestEnd - requestStart) / 1000
            );

            return response;

        } catch (Exception calloutEx) {
        
            System.debug(LoggingLevel.ERROR, calloutEx.getMessage());
            
            throw calloutEx;
        }
    }
}